#!/bin/sh
#
# gateway         This shell script takes care of starting and stopping
#                 the Kannel WAP gateway (bearer/smsbox) 
#			Fabrice Gatille <fgatille@ivision.fr>
# chkconfig: 2345 97 03
# description:  Start and stop the Kannel WAP gateway used to fetch \
#		some WML content from a Web server & compile it \
# 		into WMLC mobile phone bytecode.
# probe: true

# Use start-stop-/usr/local/sbin/run_kannel_box
START=""
CONF=/opt/kannel/etc/kannel.conf

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network



RETVAL=0

# See how we were called.
case "$1" in
  start)
        # Start /usr/local/sbin/run_kannel_boxs.
        echo -n "Starting bearer service (gateway kannel $ver): "
	/usr/local/sbin/run_kannel_box   /usr/sbin/bearerbox  $CONF
	RETVAL1=$?
	echo
	echo -n "Starting smsbox service (gateway kannel $ver): "
	/usr/local/sbin/run_kannel_box   /usr/sbin/smsbox  $CONF
	RETVAL2=$?
	echo
 	[ $RETVAL1 -eq 0 -a $RETVAL2 -eq 0 ] && touch /var/lock/subsys/gateway ||\
	RETVAL=1
        ;;
  stop)
        # Stop /usr/local/sbin/run_kannel_boxs.
	echo -n "Shutting down smsbox (kannel $ver): "
	killproc smsbox quiet
	RETVAL2=$?
	echo
	echo -n "Shutting down bearerbox (kannel $ver): "
        killproc bearerbox quiet
	RETVAL1=$?
	echo
        echo -n "Shutting down bearerbox (kannel $ver): "
        killproc /usr/local/sbin/run_kannel_box quiet
        RETVAL1=$?
        echo
	[ $RETVAL1 -eq 0 -a $RETVAL2 -eq 0 ] && rm -f /var/lock/subsys/gateway
	echo ""
        ;;
  status)
	status bearerbox
	status smsbox
	status /usr/local/sbin/run_kannel_box
	exit $?
	;;
  restart)
	$0 stop
	sleep 1
	$0 start
	;;  
  *)
        echo "Usage: named {start|stop|status|restart}"
        exit 1
esac

exit $RETVAL

